#!/bin/bash
# by @joaquinH2

ADDR=$1
AUTH=$2
SEND=$3
RECV=$4


if [[ $(echo -e "${AUTH}" | grep -i ':') ]]; then
    pUSER=$(echo -e "${AUTH}" | cut -d ':' -f1)
    CLAVE=$(echo -e "${AUTH}" | cut -d ':' -f2)
    ofusMODE=1
else
    pUSER=${AUTH}
    ofusMODE=0
fi


if [[ $(cat "/etc/passwd" | grep -w "${pUSER}") ]]; then
    FValid=$(date +%s)
    UValid=$(chage -l "${pUSER}" | grep -i co | cut -d ':' -f2)
    DataSEC=$(date +%s --date="${UValid}")


    if [[ ${FValid} -gt ${DataSEC} ]]; then
        echo -e "AUTENTIFICACION FALLIDA POR USUARIO CADUCADO : ${pUSER} "
        exit 1
    fi

   
    if [[ ${ofusMODE} = 1 ]]; then
       
        if [[ -e /etc/adm-lite/userDIR/${pUSER} ]]; then
            _PASS=$(grep "senha" /etc/adm-lite/userDIR/${pUSER} | cut -d ":" -f2 | sed 's/\s\+//g')
            LIMIT_CHECK=$(grep "limite" /etc/adm-lite/userDIR/${pUSER})

            if [[ ${LIMIT_CHECK} == *"TOKEN"* ]]; then
                
                TOKEN_PASS=$(cat /bin/ejecutar/token)

                if [[ ${CLAVE} = ${TOKEN_PASS} ]]; then
                    echo -e "AUTENTIFICACION EXITOSA PARA TOKEN : ${pUSER} "
                    exit 0
                else
                    echo -e "AUTENTIFICACION FALLIDA / CLAVE INVALIDA PARA TOKEN : ${pUSER} "
                    exit 1
                fi
            elif [[ ${LIMIT_CHECK} == *"HWID"* ]]; then
                
                if [[ ${CLAVE} = ${pUSER} ]]; then
                    echo -e "AUTENTIFICACION EXITOSA PARA HWID : ${pUSER} "
                    exit 0
                else
                    echo -e "AUTENTIFICACION FALLIDA / CLAVE INVALIDA PARA HWID : ${pUSER} "
                    exit 1
                fi
            else
                
                if [[ ${CLAVE} = ${_PASS} ]]; then
                    echo -e "AUTENTIFICACION EXITOSA / CLAVE VALIDA : ${AUTH} / ${_PASS} "
                    exit 0
                else
                    echo -e "AUTENTIFICACION FALLIDA / CLAVE INVALIDA : ${pUSER} / ${_PASS}"
                    exit 1
                fi
            fi
        else
            echo -e "AUTENTIFICACION FALLIDA / USER NO EXISTE : ${pUSER} "
            exit 1
        fi
    else
        echo -e "AUTENTIFICACION EXITOSA PARA : ${pUSER} "
        exit 0
    fi
else
    echo -e "AUTENTIFICACION FALLIDA / USER NO EXISTE : ${pUSER} "
    exit 1
fi
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
_apt:x:42:65534::/nonexistent:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-network:x:998:998:systemd Network Management:/:/usr/sbin/nologin
systemd-timesync:x:996:996:systemd Time Synchronization:/:/usr/sbin/nologin
dhcpcd:x:100:65534:DHCP Client Daemon,,,:/usr/lib/dhcpcd:/bin/false
messagebus:x:101:101::/nonexistent:/usr/sbin/nologin
syslog:x:102:102::/nonexistent:/usr/sbin/nologin
systemd-resolve:x:991:991:systemd Resolver:/:/usr/sbin/nologin
usbmux:x:103:46:usbmux daemon,,,:/var/lib/usbmux:/usr/sbin/nologin
tss:x:104:103:TPM software stack,,,:/var/lib/tpm:/bin/false
uuidd:x:105:105::/run/uuidd:/usr/sbin/nologin
sshd:x:106:65534::/run/sshd:/usr/sbin/nologin
pollinate:x:107:1::/var/cache/pollinate:/bin/false
tcpdump:x:108:108::/nonexistent:/usr/sbin/nologin
landscape:x:109:109::/var/lib/landscape:/usr/sbin/nologin
fwupd-refresh:x:990:990:Firmware update daemon:/var/lib/fwupd:/usr/sbin/nologin
polkitd:x:989:989:User for polkitd:/:/usr/sbin/nologin
